set(ITKFFT_LOADED 1)
set(ITKFFT_DEPENDS "ITKImageGrid")
set(ITKFFT_LIBRARIES "ITKCommon;ITKStatistics")
set(ITKFFT_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKFFT_LIBRARY_DIRS "")
set(ITKFFT_TARGETS_FILE "")

