set(ITKGPUPDEDeformableRegistration_LOADED 1)
set(ITKGPUPDEDeformableRegistration_DEPENDS "ITKCommon;ITKGPUCommon;ITKGPUFiniteDifference;ITKGPURegistrationCommon;ITKPDEDeformableRegistration")
set(ITKGPUPDEDeformableRegistration_LIBRARIES "ITKCommon;ITKStatistics;ITKSpatialObjects;ITKPath;ITKMesh;ITKOptimizers")
set(ITKGPUPDEDeformableRegistration_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKGPUPDEDeformableRegistration_LIBRARY_DIRS "")
set(ITKGPUPDEDeformableRegistration_TARGETS_FILE "")

