set(ITKHDF5_LOADED 1)
set(ITKHDF5_DEPENDS "ITKZLIB")
set(ITKHDF5_LIBRARIES "itkhdf5_cpp;itkhdf5")
set(ITKHDF5_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKHDF5_LIBRARY_DIRS "")
set(ITKHDF5_TARGETS_FILE "")

