set(ITKIOGE_LOADED 1)
set(ITKIOGE_DEPENDS "")
set(ITKIOGE_LIBRARIES "ITKIOGE")
set(ITKIOGE_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOGE_LIBRARY_DIRS "")
set(ITKIOGE_TARGETS_FILE "")

