set(ITKIOVTK_LOADED 1)
set(ITKIOVTK_DEPENDS "")
set(ITKIOVTK_LIBRARIES "ITKIOVTK")
set(ITKIOVTK_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOVTK_LIBRARY_DIRS "")
set(ITKIOVTK_TARGETS_FILE "")

