set(ITKIOLSM_LOADED 1)
set(ITKIOLSM_DEPENDS "")
set(ITKIOLSM_LIBRARIES "ITKIOLSM")
set(ITKIOLSM_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOLSM_LIBRARY_DIRS "")
set(ITKIOLSM_TARGETS_FILE "")

