set(ITKIOCSV_LOADED 1)
set(ITKIOCSV_DEPENDS "")
set(ITKIOCSV_LIBRARIES "ITKIOCSV")
set(ITKIOCSV_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOCSV_LIBRARY_DIRS "")
set(ITKIOCSV_TARGETS_FILE "")

