set(ITKIOXML_LOADED 1)
set(ITKIOXML_DEPENDS "ITKIOImageBase")
set(ITKIOXML_LIBRARIES "ITKIOXML")
set(ITKIOXML_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOXML_LIBRARY_DIRS "")
set(ITKIOXML_TARGETS_FILE "")

