set(ITKIONIFTI_LOADED 1)
set(ITKIONIFTI_DEPENDS "")
set(ITKIONIFTI_LIBRARIES "ITKIONIFTI")
set(ITKIONIFTI_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIONIFTI_LIBRARY_DIRS "")
set(ITKIONIFTI_TARGETS_FILE "")

