set(ITKIOJPEG_LOADED 1)
set(ITKIOJPEG_DEPENDS "")
set(ITKIOJPEG_LIBRARIES "ITKIOJPEG")
set(ITKIOJPEG_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOJPEG_LIBRARY_DIRS "")
set(ITKIOJPEG_TARGETS_FILE "")

