set(ITKIONRRD_LOADED 1)
set(ITKIONRRD_DEPENDS "")
set(ITKIONRRD_LIBRARIES "ITKIONRRD")
set(ITKIONRRD_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIONRRD_LIBRARY_DIRS "")
set(ITKIONRRD_TARGETS_FILE "")

