set(ITKIOGDCM_LOADED 1)
set(ITKIOGDCM_DEPENDS "ITKGDCM")
set(ITKIOGDCM_LIBRARIES "ITKIOGDCM")
set(ITKIOGDCM_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOGDCM_LIBRARY_DIRS "")
set(ITKIOGDCM_TARGETS_FILE "")

