set(ITKIOMRC_LOADED 1)
set(ITKIOMRC_DEPENDS "")
set(ITKIOMRC_LIBRARIES "ITKIOMRC")
set(ITKIOMRC_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOMRC_LIBRARY_DIRS "")
set(ITKIOMRC_TARGETS_FILE "")

