set(ITKIOPNG_LOADED 1)
set(ITKIOPNG_DEPENDS "")
set(ITKIOPNG_LIBRARIES "ITKIOPNG")
set(ITKIOPNG_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOPNG_LIBRARY_DIRS "")
set(ITKIOPNG_TARGETS_FILE "")

