set(ITKIOTIFF_LOADED 1)
set(ITKIOTIFF_DEPENDS "")
set(ITKIOTIFF_LIBRARIES "ITKIOTIFF")
set(ITKIOTIFF_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOTIFF_LIBRARY_DIRS "")
set(ITKIOTIFF_TARGETS_FILE "")

