set(ITKIOMeta_LOADED 1)
set(ITKIOMeta_DEPENDS "")
set(ITKIOMeta_LIBRARIES "ITKIOMeta")
set(ITKIOMeta_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOMeta_LIBRARY_DIRS "")
set(ITKIOMeta_TARGETS_FILE "")

