set(ITKIOIPL_LOADED 1)
set(ITKIOIPL_DEPENDS "")
set(ITKIOIPL_LIBRARIES "ITKIOIPL")
set(ITKIOIPL_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOIPL_LIBRARY_DIRS "")
set(ITKIOIPL_TARGETS_FILE "")

