set(ITKIOMesh_LOADED 1)
set(ITKIOMesh_DEPENDS "ITKMesh")
set(ITKIOMesh_LIBRARIES "ITKIOMesh")
set(ITKIOMesh_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOMesh_LIBRARY_DIRS "")
set(ITKIOMesh_TARGETS_FILE "")

