set(ITKIOHDF5_LOADED 1)
set(ITKIOHDF5_DEPENDS "")
set(ITKIOHDF5_LIBRARIES "ITKIOHDF5")
set(ITKIOHDF5_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOHDF5_LIBRARY_DIRS "")
set(ITKIOHDF5_TARGETS_FILE "")

