set(ITKIOBioRad_LOADED 1)
set(ITKIOBioRad_DEPENDS "")
set(ITKIOBioRad_LIBRARIES "ITKIOBioRad")
set(ITKIOBioRad_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOBioRad_LIBRARY_DIRS "")
set(ITKIOBioRad_TARGETS_FILE "")

