set(ITKIOBMP_LOADED 1)
set(ITKIOBMP_DEPENDS "")
set(ITKIOBMP_LIBRARIES "ITKIOBMP")
set(ITKIOBMP_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKIOBMP_LIBRARY_DIRS "")
set(ITKIOBMP_TARGETS_FILE "")

