set(ITKJPEG_LOADED 1)
set(ITKJPEG_DEPENDS "")
set(ITKJPEG_LIBRARIES "itkjpeg")
set(ITKJPEG_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKJPEG_LIBRARY_DIRS "")
set(ITKJPEG_TARGETS_FILE "")

