set(ITKMesh_LOADED 1)
set(ITKMesh_DEPENDS "")
set(ITKMesh_LIBRARIES "ITKMesh")
set(ITKMesh_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKMesh_LIBRARY_DIRS "")
set(ITKMesh_TARGETS_FILE "")

