set(ITKMetaIO_LOADED 1)
set(ITKMetaIO_DEPENDS "ITKZLIB")
set(ITKMetaIO_LIBRARIES "ITKMetaIO")
set(ITKMetaIO_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKMetaIO_LIBRARY_DIRS "")
set(ITKMetaIO_TARGETS_FILE "")

