set(ITKNIFTI_LOADED 1)
set(ITKNIFTI_DEPENDS "ITKZLIB")
set(ITKNIFTI_LIBRARIES "ITKznz;ITKniftiio")
set(ITKNIFTI_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKNIFTI_LIBRARY_DIRS "")
set(ITKNIFTI_TARGETS_FILE "")

