set(ITKTestKernel_LOADED 1)
set(ITKTestKernel_DEPENDS "ITKDoubleConversion;ITKIOBMP;ITKIOGDCM;ITKIOGIPL;ITKIOImageBase;ITKIOJPEG;ITKIOMeta;ITKIONIFTI;ITKIONRRD;ITKIOPNG;ITKIOTIFF;ITKIOVTK;ITKKWSys")
set(ITKTestKernel_LIBRARIES "ITKCommon;itkdouble-conversion;ITKIOBMP;ITKIOGDCM;ITKIOGIPL;ITKIOImageBase;ITKIOJPEG;ITKIOMeta;ITKIONIFTI;ITKIONRRD;ITKIOPNG;ITKIOTIFF;ITKIOVTK;itksys")
set(ITKTestKernel_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.9")
set(ITKTestKernel_LIBRARY_DIRS "")
set(ITKTestKernel_TARGETS_FILE "")

